
version: '3.9'

services:
    db:
        container_name: '${APP_NAME}db'
        image: postgres
        volumes:
            - storage_db:/var/lib/postgres/data
            - ./portugues.sql:/docker-entrypoint-initdb.d/portugues.sql
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${DB_USER}@admin.com
            PGADMIN_DEFAULT_PASSWORD: ${DB_PASS}
        ports:
            - "5050:80"
